/**
 * 
 */
$(document).ready(function(){
	$('#signIn').click(function(){
		$('.over').fadeIn();
		$('.sign-in').fadeIn();
	});
	$('#submitSignIn').click(function(){
		$('.over').fadeOut();
		$('.sign-in').fadeOut();
	});
	$('#signUp').click(function(){
		$('.over').fadeIn();
		$('.sign-up').fadeIn();
	});
});